# Generated by Django 6.0.4 on 2026-06-05 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0004_alter_llmcalllog_model"),
        ("courses", "0005_announcement"),
        ("knowledge", "0007_resource_processing_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("profile_dialog", "画像对话"),
                            ("resource_generation", "资源生成"),
                            ("learning_package", "学习包生成"),
                        ],
                        max_length=40,
                        verbose_name="运行类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "input_text",
                    models.TextField(blank=True, default="", verbose_name="输入内容"),
                ),
                (
                    "profile_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="画像快照"),
                ),
                (
                    "agent_trace",
                    models.JSONField(
                        blank=True, default=list, verbose_name="智能体轨迹"
                    ),
                ),
                (
                    "result_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="运行结果"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent运行记录",
                "verbose_name_plural": "Agent运行记录",
                "db_table": "agent_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedLearningResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("explanation", "讲解文档"),
                            ("mindmap", "思维导图"),
                            ("quiz", "练习题"),
                            ("reading", "拓展阅读"),
                            ("coding_case", "代码实操案例"),
                            ("video_script", "视频脚本"),
                        ],
                        max_length=40,
                        verbose_name="资源类型",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "evidence",
                    models.JSONField(blank=True, default=list, verbose_name="证据来源"),
                ),
                (
                    "profile_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="画像快照"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_resources",
                        to="ai_services.agentrun",
                        verbose_name="运行记录",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_learning_resources",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_learning_resources",
                        to="knowledge.knowledgepoint",
                        verbose_name="知识点",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_learning_resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成学习资源",
                "verbose_name_plural": "生成学习资源",
                "db_table": "generated_learning_resources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileDialogTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "学生"),
                            ("assistant", "助手"),
                            ("system", "系统"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "extracted_slots",
                    models.JSONField(blank=True, default=dict, verbose_name="抽取字段"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialog_turns",
                        to="ai_services.agentrun",
                        verbose_name="运行记录",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_dialog_turns",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_dialog_turns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "画像对话轮次",
                "verbose_name_plural": "画像对话轮次",
                "db_table": "profile_dialog_turns",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedResourceFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="评分",
                    ),
                ),
                (
                    "usefulness",
                    models.CharField(
                        choices=[
                            ("useful", "有帮助"),
                            ("neutral", "一般"),
                            ("not_useful", "无帮助"),
                        ],
                        default="neutral",
                        max_length=20,
                        verbose_name="有用性",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "偏简单"),
                            ("moderate", "适中"),
                            ("hard", "偏困难"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, default="", verbose_name="文本反馈"),
                ),
                (
                    "quiz_result",
                    models.JSONField(blank=True, default=dict, verbose_name="练习结果"),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="学习耗时秒数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_records",
                        to="ai_services.generatedlearningresource",
                        verbose_name="生成资源",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_resource_feedback",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成资源反馈",
                "verbose_name_plural": "生成资源反馈",
                "db_table": "generated_resource_feedback",
                "ordering": ["-created_at"],
                "unique_together": {("resource", "user")},
            },
        ),
    ]
